### ISSUE TITLE
Walkcycle not functioning as intended

### ISSUE THREAD

**Issue by koshisan** [kevinmcaleer/SMARSLab#27]
Hi,

I thought this might be the better place to keep track of issues than youtube ;)

No pressure, I understand that you have a daytimejob and this is a hobby project, but I build my SMARS just yesterday, so I am quite exited about it. Who knows, maybe it's even motivating if you are not the only one writing here ;)

While I do have some programming experience, I haven't done anything with python so far - but I should be able to help out with basic diagnostics and stuff.

As for the specific problem:

It is like you mentioned in your video. Currently the walking doesn't work correctly. The feet are moving, but the legs basically move only in one position at the start of the cycle and then remain there.

I guess the problem is somewhere in def walkforward of smars_library.py...

**Comment by kevinmcaleer** [comment]
# Issue replicated
Looking into this issue, I've replicated this issue. I think its in the `smars_library` tick code. I'm going to step through this one line at a time to track down the issue.

**Comment by kevinmcaleer** [comment]
I've fixed this issue. If you do a ‘pip install smars_library --upgrade’ it should fix the issue
